name: combos_tv
description: The soccer watch app
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player_web_hls: ^1.0.0+2
  video_player: ^2.5.1
  flutter_lints: ^2.0.0
  babstrap_settings_screen: ^0.1.4
  font_awesome_flutter: ^10.3.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^7.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/tournamets.json
